webtalk_init -webtalk_dir C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.sim/sim_1/behav/xsim/xsim.dir/tb_brainiac_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Dec 26 11:46:31 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cd78195d-2be3-4fa5-b93d-0851a58d43ac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "433d1b3cbd84478a9ea5efec90a079e5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "691" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "44" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "353 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "84 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "1299" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "167" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "9.87_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "236820_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2860431685 -regid "" -xml C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.sim/sim_1/behav/xsim/xsim.dir/tb_brainiac_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.sim/sim_1/behav/xsim/xsim.dir/tb_brainiac_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.sim/sim_1/behav/xsim/xsim.dir/tb_brainiac_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
