# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.srcs/sources_1/ip/brom_8x65k/brom_8x65k.xci
# IP: The module: 'brom_8x65k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.gen/sources_1/ip/brom_8x65k/brom_8x65k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'brom_8x65k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.srcs/sources_1/ip/brom_8x65k/brom_8x65k.xci
# IP: The module: 'brom_8x65k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Curtis Bucher/OneDrive - Cal Poly/braiNIAC/braiNIAC.gen/sources_1/ip/brom_8x65k/brom_8x65k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'brom_8x65k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
