# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Curtis Bucher/OneDrive - Cal Poly/CPE 133/VivadoProjects/braiNIAC/braiNIAC.srcs/sources_1/ip/counter/counter.xci
# IP: The module: 'counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Curtis Bucher/OneDrive - Cal Poly/CPE 133/VivadoProjects/braiNIAC/braiNIAC.gen/sources_1/ip/counter/counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Curtis Bucher/OneDrive - Cal Poly/CPE 133/VivadoProjects/braiNIAC/braiNIAC.srcs/sources_1/ip/counter/counter.xci
# IP: The module: 'counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Curtis Bucher/OneDrive - Cal Poly/CPE 133/VivadoProjects/braiNIAC/braiNIAC.gen/sources_1/ip/counter/counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
